name: Albus Image DP

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: SaaSD3v/recovery-console/.github/workflows/albus-image-dp.yml@albus-image-dp
    secrets: inherit
