name: Channel Image DP

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: SaaSD3v/recovery-console/.github/workflows/recovery-image-builder.yml@channel-image-dp
    secrets: inherit
